# Generated by Django 5.1.5 on 2025-02-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_mymodel_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_counter',
            field=models.PositiveIntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='Счетчик просмотров'),
        ),
    ]
